name: validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1"

      - name: terraform fmt check
        run: terraform fmt -check -recursive

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate

      - name: terraform init (examples)
        working-directory: examples/basic
        run: terraform init -backend=false

      - name: terraform validate (examples)
        working-directory: examples/basic
        run: terraform validate

      - name: tflint setup
        uses: terraform-linters/setup-tflint@v4

      - name: tflint init
        run: tflint --init

      - name: tflint
        run: tflint

      - name: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          soft_fail: true

      - name: terraform-docs check
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          fail-on-diff: true
